const express = require('express');
const app = express();
const PORT = 3000;
const jokes = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "What do you call a lazy kangaroo? A pouch potato!",
  "Why did the golfer wear two pairs of pants? In case he got a hole-in-one!",
  "What do you call a bear with no teeth? A gummy bear!",
  "What do you call a fish with no eyes? Fsh!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't they play poker in the jungle? Too many cheetahs!",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "What do you call a lazy kangaroo? A pouch potato!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the golfer wear two pairs of pants? In case he got a hole-in-one!",
  "What do you call a fish with no eyes? Fsh!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't they play poker in the jungle? Too many cheetahs!",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "What do you call a lazy kangaroo? A pouch potato!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the golfer wear two pairs of pants? In case he got a hole-in-one!",
  "What do you call a fish with no eyes? Fsh!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't they play poker in the jungle? Too many cheetahs!",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "What do you call a lazy kangaroo? A pouch potato!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the golfer wear two pairs of pants? In case he got a hole-in-one!",
  "What do you call a fish with no eyes? Fsh!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't they play poker in the jungle? Too many cheetahs!",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "What do you call a lazy kangaroo? A pouch potato!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the golfer wear two pairs of pants? In case he got a hole-in-one!",
  "What do you call a fish with no eyes? Fsh!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't they play poker in the jungle? Too many cheetahs!",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "What do you call a lazy kangaroo? A pouch potato!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the golfer wear two pairs of pants? In case he got a hole-in-one!",
  "What do you call a fish with no eyes? Fsh!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't they play poker in the jungle? Too many cheetahs!",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "What do you call a lazy kangaroo? A pouch potato!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the golfer wear two pairs of pants? In case he got a hole-in-one!",
  "What do you call a fish with no eyes? Fsh!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't they play poker in the jungle? Too many cheetahs!",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "What do you call a lazy kangaroo? A pouch potato!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the golfer wear two pairs of pants? In case he got a hole-in-one!",
  "What do you call a fish with no eyes? Fsh!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't they play poker in the jungle? Too many cheetahs!",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus!",
  "Why don't they serve beer at a math party? Because it would be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!",
  "Why don't they serve beer at a math party? Because it would we be too irrational!",
  "What do you call a cow with no legs? Ground beef!",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a sad strawberry? A blueberry!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What do you call a fake noodle? An impasta!"
];

app.get('/Minato', (req, res) => {
   
    const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
  
    res.json(randomQuote);
});

app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});
